// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.relon.grpcproto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.relon.grpcproto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
